Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  5 2014, 20:42:22) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "copyright", "credits" or "license()" for more information.
>>> WARNING: The version of Tcl/Tk (8.5.9) in use may be unstable.
Visit http://www.python.org/download/mac/tcltk/ for current information.
joke_text = '%s: a device for finding furniture in the dark'
>>> bodypart1 = Knee
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    bodypart1 = Knee
NameError: name 'Knee' is not defined
>>> '%s: a device for finding furniture in the dark'
'%s: a device for finding furniture in the dark'
>>> bodypart1 = 'knee'
>>> bodypart2 = 'shin'
>>> print (joke_text % bodypart1)
knee: a device for finding furniture in the dark
>>> print (joke_text % bodypart2)
shin: a device for finding furniture in the dark
>>> joke_text = '%s: a large snake'
>>> bodypart1 = 'willy'
>>> print (joke_text % bodypart1)
willy: a large snake
>>> little pigs and cows = 'what did the big %s say to the little %s nice colour'
SyntaxError: invalid syntax
>>> nums = 'What did the number %s say to the number %s nice belt!!'
>>> print (nums % (0, 8))
What did the number 0 say to the number 8 nice belt!!
>>> bit_in_book = 'the bit in the book is called multiplying strings'
>>> print (bit_in_book)
the bit in the book is called multiplying strings
>>> print (10 * a)
Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    print (10 * a)
NameError: name 'a' is not defined
>>> print (10 * 'a')
aaaaaaaaaa
>>> spaces = ' ' * 25
Print ('%s 12 butts wynd' % spaces)
print ('%s twinklebottom health' % spaces)
print ('%s west snoring' % spaces)
print ()
print ()
print ('dear sir')
print ()
print ('i wish to report that tiles are missing from the')
print ('outside toilet roof.')
print ('i think it was bad wind the other night that blew them away.')
print ()
print ('regards')
print ('Malcolm Dithering')

SyntaxError: multiple statements found while compiling a single statement
>>> print(1000 * snirt)
Traceback (most recent call last):
  File "<pyshell#19>", line 1, in <module>
    print(1000 * snirt)
NameError: name 'snirt' is not defined
>>> print(1000 * 'snirt')
snirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirtsnirt
>>> annoying
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    annoying
NameError: name 'annoying' is not defined
>>> print(1000 * 'annoying
      
SyntaxError: EOL while scanning string literal
>>> print(1000 * 'annoying')
annoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoyingannoying
>>> wizard_magix = 'spider legs, toe of frog, eye of newt, bat wing, slug butter,snake dandruff'
>>> print(wizard_magix)
spider legs, toe of frog, eye of newt, bat wing, slug butter,snake dandruff
>>> wizard_magix = ['spider legs, toe of frog, eye of newt, bat wing, slug butter,snake dandruff']
>>> print(wizard_magix)
['spider legs, toe of frog, eye of newt, bat wing, slug butter,snake dandruff']
>>> print(wizard_magix [2])
Traceback (most recent call last):
  File "<pyshell#28>", line 1, in <module>
    print(wizard_magix [2])
IndexError: list index out of range
>>> 
>>> print(wizard_magix [3])
Traceback (most recent call last):
  File "<pyshell#30>", line 1, in <module>
    print(wizard_magix [3])
IndexError: list index out of range
>>> print(wizard_magix[2])
Traceback (most recent call last):
  File "<pyshell#31>", line 1, in <module>
    print(wizard_magix[2])
IndexError: list index out of range
>>> print(wizard_magix[3])
Traceback (most recent call last):
  File "<pyshell#32>", line 1, in <module>
    print(wizard_magix[3])
IndexError: list index out of range
>>> 
